name: Next.js Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Check commit messages
        run: npm run commitlint
      - name: Run unit tests
        run: npm run test
      - name: Run build
        run: npm run build
